import { gql } from "@apollo/client";

export const CAN_SUBSCRIPTION = gql`
  subscription {
    can {
      Front_Brake_Pressure
      Rear_Break_Pressure
      Throttle_Pos_Primary
      Throttle_Pos_Secondary
      FR_Wheel_Speed
      FL_Wheel_Speed
      RR_Wheel_Speed
      RL_Wheel_Speed
      Steering_Pot_Primary
      Steering_Pot_Secondary
      Motor_One_Cooling_Loop_Temp_Out
      Motor_One_Cooling_Loop_Temp_In
      Motor_Two_Cooling_Loop_Temp_Out
      Motor_Two_Cooling_Loop_Temp_In
      Inverter_Cooling_Loop_Temp_Out
      Inverter_Cooling_Loop_Temp_In
      Gearbox_One_Temp
      Gearbox_Two_Temp
      Front_IMU_Lateral_Accel
      Front_IMU_Long_Accel
      Front_IMU_Vert_Accel
      Front_IMU_Yaw_Rotate
      Front_IMU_Pitch_Rotate
      Front_IMU_Roll_Rotate
      Inv_One_Status_Word
      Inv_One_Actual_Speed
      Inv_One_Actual_Torque_Current
      Inv_One_Actual_Magnetizing_Current
      Inv_Two_Status_Word
      Inv_Two_Actual_Speed_Value
      Inv_Two_Torque_Current
      Inv_Two_Actual_Magnetizing_Current
      Pack_Current
      Pack_Inst_Voltage
      Pack_SOC
      Relay_State
      Pack_DCL
      Pack_CCL
      Lowest_Temp
      Highest_Temp
      Low_Cell_ID
      High_Cell_ID
      Low_Termistor_ID
      High_Thermistor_ID
      Internal_Temp
      Average_Temp
      Pack_Health
      DTC_Flags_One
      DTC_Flags_Two
      Current_Limit_Status
      Ready_To_Drive_Input
      Ready_To_Drive_Arm_Inverters
      Traction_Control_Setting
      Torque_Vectoring_Low_Setting
      Torque_Vectoring_High_Setting
      Low_Cell_Voltage
      High_Cell_Voltage
    }
  }
`;
